package com.myspace.proyectosalvavidas.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Accion")
public class Accion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "accionInformativa")
	private java.lang.String accionInformativa;
	@org.kie.api.definition.type.Label(value = "accionGestion")
	private java.lang.String accionGestion;

	public Accion() {
	}

	public java.lang.String getAccionInformativa() {
		return this.accionInformativa;
	}

	public void setAccionInformativa(java.lang.String accionInformativa) {
		this.accionInformativa = accionInformativa;
	}

	public java.lang.String getAccionGestion() {
		return this.accionGestion;
	}

	public void setAccionGestion(java.lang.String accionGestion) {
		this.accionGestion = accionGestion;
	}

	public Accion(java.lang.String accionInformativa,
			java.lang.String accionGestion) {
		this.accionInformativa = accionInformativa;
		this.accionGestion = accionGestion;
	}

}