package com.myspace.proyectosalvavidas.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Evaluacion")
public class Evaluacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "CC")
	private java.lang.String CC;
	@org.kie.api.definition.type.Label(value = "NE")
	private java.lang.String NE;
	@org.kie.api.definition.type.Label(value = "MR")
	private java.lang.String MR;
	@org.kie.api.definition.type.Label(value = "CM")
	private java.lang.String CM;
	@org.kie.api.definition.type.Label(value = "RP")
	private java.lang.String RP;
	@org.kie.api.definition.type.Label(value = "EC")
	private java.lang.String EC;
	@org.kie.api.definition.type.Label(value = "PC")
	private java.lang.String PC;

	public Evaluacion() {
	}

	public java.lang.String getCC() {
		return this.CC;
	}

	public void setCC(java.lang.String CC) {
		this.CC = CC;
	}

	public java.lang.String getNE() {
		return this.NE;
	}

	public void setNE(java.lang.String NE) {
		this.NE = NE;
	}

	public java.lang.String getMR() {
		return this.MR;
	}

	public void setMR(java.lang.String MR) {
		this.MR = MR;
	}

	public java.lang.String getCM() {
		return this.CM;
	}

	public void setCM(java.lang.String CM) {
		this.CM = CM;
	}

	public java.lang.String getRP() {
		return this.RP;
	}

	public void setRP(java.lang.String RP) {
		this.RP = RP;
	}

	public java.lang.String getEC() {
		return this.EC;
	}

	public void setEC(java.lang.String EC) {
		this.EC = EC;
	}

	public java.lang.String getPC() {
		return this.PC;
	}

	public void setPC(java.lang.String PC) {
		this.PC = PC;
	}

	public Evaluacion(java.lang.String CC, java.lang.String NE,
			java.lang.String MR, java.lang.String CM, java.lang.String RP,
			java.lang.String EC, java.lang.String PC) {
		this.CC = CC;
		this.NE = NE;
		this.MR = MR;
		this.CM = CM;
		this.RP = RP;
		this.EC = EC;
		this.PC = PC;
	}

}