package com.myspace.proyectosalvavidas.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("NombreValor")
public class NombreValor implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label("valor")
	private Integer valor;

	public NombreValor() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.Integer getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Integer valor) {
		this.valor = valor;
	}

	public NombreValor(java.lang.String nombre, java.lang.Integer valor) {
		this.nombre = nombre;
		this.valor = valor;
	}

}