package com.myspace.proyectosalvavidas.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Persona")
public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("edad")
	private java.lang.Integer edad;
	@org.kie.api.definition.type.Label("orientacion")
	private java.lang.Boolean orientacion;
	@org.kie.api.definition.type.Label("prioridad")
	private java.lang.Integer prioridad;

	@org.kie.api.definition.type.Label(value = "sintomas")
	private java.util.List<com.myspace.proyectosalvavidas.modelo.Sintoma> sintomas;

	public Persona() {
	}

	public java.lang.Integer getEdad() {
		return this.edad;
	}

	public void setEdad(java.lang.Integer edad) {
		this.edad = edad;
	}

	public java.lang.Boolean getOrientacion() {
		return this.orientacion;
	}

	public void setOrientacion(java.lang.Boolean orientacion) {
		this.orientacion = orientacion;
	}

	public java.lang.Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(java.lang.Integer prioridad) {
		this.prioridad = prioridad;
	}

	public java.util.List<com.myspace.proyectosalvavidas.modelo.Sintoma> getSintomas() {
		return this.sintomas;
	}

	public void setSintomas(
			java.util.List<com.myspace.proyectosalvavidas.modelo.Sintoma> sintomas) {
		this.sintomas = sintomas;
	}

	public Persona(
			java.lang.Integer edad,
			java.lang.Boolean orientacion,
			java.lang.Integer prioridad,
			java.util.List<com.myspace.proyectosalvavidas.modelo.Sintoma> sintomas) {
		this.edad = edad;
		this.orientacion = orientacion;
		this.prioridad = prioridad;
		this.sintomas = sintomas;
	}

}