package com.myspace.proyectosalvavidas.modelo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Sintoma")
public class Sintoma implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "valor")
	private java.lang.String valor;

	public Sintoma() {
	}

	public java.lang.String getValor() {
		return this.valor;
	}

	public void setValor(java.lang.String valor) {
		this.valor = valor;
	}

	public Sintoma(java.lang.String valor) {
		this.valor = valor;
	}

}